[package]
name = "spider"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.1.1"
endianness = "0.2.0"
flate2 = "1.0.34"
hex = "0.4.3"
regex = "1.10.6"
reqwest = {verson = "0.12.5", features = ["blocking"]}
scraper = "0.19.1"

